import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:sqflite/sqflite.dart';

import '../database/database_helper.dart';
import '../models/inventory.dart';
import 'species_dao.dart';
import 'vegetation_dao.dart';
import 'weather_dao.dart';

import '../../utils/utils.dart';

/// Provides persistence helpers for inventories and their aggregate queries.
class InventoryDao {
  final DatabaseHelper _dbHelper;
  final SpeciesDao _speciesDao;
  final VegetationDao _vegetationDao;
  final WeatherDao _weatherDao;

  InventoryDao(this._dbHelper, this._speciesDao, this._vegetationDao, this._weatherDao);

  /// Inserts a new [Inventory] record into the database.
  ///
  /// Automatically sets [Inventory.startTime] to the current date/time and,
  /// if location permission is available, populates [Inventory.startLatitude]
  /// and [Inventory.startLongitude] from the device's current position.
  /// Uses [ConflictAlgorithm.replace] to handle duplicate entries.
  /// Returns `true` on success, or `false` if a database or generic error occurs.
  Future<bool> insertInventory(BuildContext context, Inventory inventory) async {
    final db = await _dbHelper.database;
    try {
      inventory.startTime = DateTime.now();
      Position? position = await getPosition(context);
      if (position != null) {
        inventory.startLatitude = position.latitude;
        inventory.startLongitude = position.longitude;
      }

      int? recordId = await db?.insert(
        'inventories',
        inventory.toMap(),
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      return recordId != null && recordId > 0;
    } on DatabaseException catch (e) {
      debugPrint('Database error: $e');
      debugPrint('Exception type: ${e.runtimeType}');
      debugPrint('Detailed message: ${e.toString()}');
      return false;
      // Handle the database error
    } catch (e) {
      debugPrint('Generic error: $e');
      debugPrint('Exception type: ${e.runtimeType}');
      debugPrint('Detailed message: ${e.toString()}');
      // Handle other errors
      return false;
    }
  }

  /// Imports an [Inventory] into the database inside a single transaction,
  /// ignoring any pre-existing IDs on child records so the database assigns
  /// new auto-incremented IDs.
  ///
  /// The imported inventory is always marked as finished. After inserting the
  /// inventory, all associated [Species] (with their [Poi]s), [Vegetation], and
  /// [Weather] records are inserted and linked to the inventory's ID.
  /// The transaction is rolled back entirely if any insertion fails.
  /// Returns `true` on success, or `false` if an error occurs.
  Future<bool> importInventory(Inventory inventory) async {
    final db = await _dbHelper.database;
    if (db == null) {
      debugPrint('[DAO] !!! ERROR importing inventory: Database instance is null.');
      return false;
    }

    try {
      return await db.transaction((txn) async {
        inventory.isFinished = true;
        // The inventory.id might be pre-set if it's an import.
        // If it's meant to be auto-generated by the DB, it should be null here.
        // However, ConflictAlgorithm.replace handles existing IDs.
        // Let's assume inventory.id is the intended ID for the imported record.
        int? recordId = await txn.insert(
          'inventories',
          inventory.toMap(),
          conflictAlgorithm: ConflictAlgorithm.replace,
        );

        // It's crucial that inventory.id is correctly set for foreign keys.
        // If recordId is from an auto-incrementing PK and inventory.id was different,
        // this could be an issue. Assuming inventory.id is the source of truth.
        final String currentInventoryId = inventory.id; // Assuming inventory.id is non-null and is the key

        for (final species in inventory.speciesList) {
          species.id = null; // Ensure new ID from DB
          int? speciesId = await txn.insert(
            'species',
            species.toMap(currentInventoryId), // Use the parent inventory's ID
            conflictAlgorithm: ConflictAlgorithm.replace,
          );
          species.id = speciesId; // Update object with new DB-generated ID

          if (speciesId <= 0) {
            // If species insertion failed, the transaction will roll back.
            // We can throw an exception to ensure rollback.
            throw Exception('Failed to insert species: ${species.toString()}');
          }

          for (final poi in species.pois) {
            poi.id = null; // Ensure new ID from DB
            int? poiId = await txn.insert(
              'pois',
              poi.toMap(speciesId), // Use the parent species' new ID
              conflictAlgorithm: ConflictAlgorithm.replace,
            );
            poi.id = poiId; // Update object with new DB-generated ID
            if (poiId <= 0) {
              throw Exception('Failed to insert POI: ${poi.toString()}');
            }
          }
        }

        for (final vegetation in inventory.vegetationList) {
          vegetation.id = null; // Ensure new ID from DB
          int? vegetationId = await txn.insert(
            'vegetation',
            vegetation.toMap(currentInventoryId), // Use the parent inventory's ID
            conflictAlgorithm: ConflictAlgorithm.replace,
          );
          vegetation.id = vegetationId; // Update object with new DB-generated ID
          if (vegetationId <= 0) {
            throw Exception('Failed to insert vegetation: ${vegetation.toString()}');
          }
        }

        for (final weather in inventory.weatherList) {
          weather.id = null; // Ensure new ID from DB
          int? weatherId = await txn.insert(
            'weather',
            weather.toMap(currentInventoryId), // Use the parent inventory's ID
            conflictAlgorithm: ConflictAlgorithm.replace,
          );
          weather.id = weatherId; // Update object with new DB-generated ID
          if (weatherId <= 0) {
            throw Exception('Failed to insert weather: ${weather.toString()}');
          }
        }

        return recordId > 0;
      });
    } on DatabaseException catch (e) {
      debugPrint('Database error during importInventory transaction: $e');
      debugPrint('Exception type: ${e.runtimeType}');
      debugPrint('Detailed message: ${e.toString()}');
      return false;
    } catch (e) {
      debugPrint('Generic error during importInventory transaction: $e');
      debugPrint('Exception type: ${e.runtimeType}');
      debugPrint('Detailed message: ${e.toString()}');
      return false;
    }
  }

  /// Deletes the [Inventory] record identified by [inventoryId] from the database.
  Future<void> deleteInventory(String? inventoryId) async {
    final db = await _dbHelper.database;
    await db?.delete(
      'inventories',
      where: 'id = ?',
      whereArgs: [inventoryId],
    );
  }

  /// Updates the database record for the given [inventory] using its [Inventory.id].
  Future<void> updateInventory(Inventory inventory) async {
    try {
      final db = await _dbHelper.database;
      await db?.update(
        'inventories',
        inventory.toMap(),
        where: 'id = ?',
        whereArgs: [inventory.id],
      );
      debugPrint('[DAO] Inventory updated: ${inventory.id}');
    } catch (e) {
      debugPrint('[DAO] !!! ERROR updating inventory: $e');
    }
  }

  /// Updates only the `elapsedTime` field of the inventory identified by
  /// [inventoryId] to [elapsedTime].
  Future<void> updateInventoryElapsedTime(String inventoryId, double elapsedTime) async {
    final db = await _dbHelper.database;
    await db?.update(
      'inventories',
      {'elapsedTime': elapsedTime},
      where: 'id = ?',
      whereArgs: [inventoryId],
    );
  }

  /// Updates only the `currentInterval` field of the inventory identified by
  /// [inventoryId] to [currentInterval].
  Future<void> updateInventoryCurrentInterval(String inventoryId, int currentInterval) async {
    final db = await _dbHelper.database;
    await db?.update(
      'inventories',
      {'currentInterval': currentInterval},
      where: 'id = ?',
      whereArgs: [inventoryId],
    );
  }

  /// Updates only the `intervalsWithoutNewSpecies` field of the inventory
  /// identified by [inventoryId] to [intervalsWithoutSpecies].
  Future<void> updateInventoryIntervalsWithoutSpecies(String inventoryId, int intervalsWithoutSpecies) async {
    final db = await _dbHelper.database;
    await db?.update(
      'inventories',
      {'intervalsWithoutNewSpecies': intervalsWithoutSpecies},
      where: 'id = ?',
      whereArgs: [inventoryId],
    );
  }

  /// Updates only the `currentIntervalSpeciesCount` field of the inventory
  /// identified by [inventoryId] to [speciesCount].
  Future<void> updateInventoryCurrentIntervalSpeciesCount(String inventoryId, int speciesCount) async {
    final db = await _dbHelper.database;
    await db?.update(
      'inventories',
      {'currentIntervalSpeciesCount': speciesCount},
      where: 'id = ?',
      whereArgs: [inventoryId],
    );
  }

  /// Renames an inventory's primary key from [oldId] to [newId], also updating
  /// the `inventoryId` foreign key in the `species`, `vegetation`, and `weather`
  /// tables inside a single transaction.
  ///
  /// Foreign-key enforcement is temporarily disabled during the operation to
  /// allow the primary-key update without constraint violations.
  /// Throws an [Exception] if the database is unavailable, if no inventory with
  /// [oldId] is found, or if a database error occurs.
  Future<void> changeInventoryId(String oldId, String newId) async {
    final db = await _dbHelper.database;

    // 1. Check if database connection is available
    if (db == null) {
      debugPrint('[DAO] !!! ERROR changing inventory ID: Database connection is not available.');
      throw Exception('Database connection is not available.');
    }

    try {
      await db.execute('PRAGMA foreign_keys = OFF;');
      // 2. Run transaction logic
      await db.transaction((txn) async {

        // 3. Update the main table 'inventories'.
        int inventoryUpdated = await txn.update(
          'inventories',
          {'id': newId},
          where: 'id = ?',
          whereArgs: [oldId],
        );

        // 4. Crucial check: if main record was not found, stop transaction
        if (inventoryUpdated == 0) {
          debugPrint('[DAO] !!! ERROR changing inventory ID: Inventory with old ID "$oldId" not found. Transaction rolled back.');
          throw Exception('Inventory with old ID "$oldId" not found. Transaction rolled back.');
        }

        // 5. Update related tables with the 'inventoryId'.
        await txn.update(
          'species',
          {'inventoryId': newId},
          where: 'inventoryId = ?',
          whereArgs: [oldId],
        );

        await txn.update(
          'vegetation',
          {'inventoryId': newId},
          where: 'inventoryId = ?',
          whereArgs: [oldId],
        );

        await txn.update(
          'weather',
          {'inventoryId': newId},
          where: 'inventoryId = ?',
          whereArgs: [oldId],
        );
      });
      await db.execute('PRAGMA foreign_keys = ON;');

      debugPrint('[DAO] ...Successfully changed inventory ID from "$oldId" to "$newId"');

    } on DatabaseException catch (e, s) {
      // 6. Capture database errors (e.g.: constraint violation)
      debugPrint('[DAO] !!! DATABASE ERROR changing inventory ID: $e');
      debugPrint('Stack trace: $s');
      throw Exception('Failed to change inventory ID due to a database error: $e');
    } catch (e) {
      // 7. Capture other errors
      debugPrint('[DAO] !!! ERROR changing inventory ID: $e');
      rethrow;
    }
  }

  /// Returns `true` if an inventory with the given [id] already exists in the
  /// database (case-insensitive comparison).
  Future<bool> inventoryIdExists(String id) async {
    final db = await _dbHelper.database;
    final result = await db?.query(
      'inventories',
      where: 'LOWER(id) = ?',
      whereArgs: [id.toLowerCase()],
    );
    return result!.isNotEmpty;
  }

  /// Returns the number of inventories that have not yet been finished
  /// (`isFinished = 0`).
  Future<int> getActiveInventoriesCount() async {
    final db = await _dbHelper.database;
    final result = await db?.rawQuery('SELECT COUNT(*) FROM inventories WHERE isFinished = 0');
    return Sqflite.firstIntValue(result!) ?? 0;
  }

  /// Returns all [Inventory] records from the database, each populated with
  /// its associated [Species], [Vegetation], and [Weather] lists.
  Future<List<Inventory>> getInventories() async {
    final db = await _dbHelper.database;
    try {
      final List<Map<String, dynamic>> maps = await db?.query('inventories') ?? [];

      List<Inventory> inventories = await Future.wait(maps.map((map) async {
        List<Species> speciesList = await _speciesDao.getSpeciesByInventory(map['id'], false);
        List<Vegetation> vegetationList = await _vegetationDao.getVegetationByInventory(map['id']);
        List<Weather> weatherList = await _weatherDao.getWeatherByInventory(map['id']);

        Inventory inventory = Inventory.fromMap(map, speciesList, vegetationList, weatherList);

        return inventory;
      }).toList());

      debugPrint('[DAO] Loaded inventories: ${inventories.length}');

      return inventories;
    } catch (e) {
      debugPrint('[DAO] !!! ERROR loading inventories: $e');

      // Handle the error, e.g.: return an empty list or rethrow exception
      return []; // Or rethrow;
    }
  }

  /// Returns the [Inventory] identified by [id], populated with its associated
  /// [Species], [Vegetation], and [Weather] lists.
  ///
  /// Throws an [Exception] if no inventory with the given ID is found.
  Future<Inventory> getInventoryById(String id) async {
    final db = await _dbHelper.database;
    final List<Map<String, dynamic>> maps = await db?.query(
        'inventories',
        where: 'id = ?',
        whereArgs: [id]
    ) ?? [];
    if (maps.isNotEmpty) {
      final map = maps.first;
      List<Species> speciesList = await _speciesDao.getSpeciesByInventory(map['id'], false);
      List<Vegetation> vegetationList = await _vegetationDao.getVegetationByInventory(map['id']);
      List<Weather> weatherList = await _weatherDao.getWeatherByInventory(map['id']);
      return Inventory.fromMap(map, speciesList, vegetationList, weatherList);
    } else {
      throw Exception('Inventory not found with ID $id');
    }
  }

  /// Returns the next available sequential number for an inventory ID, based on
  /// the optional locality [local], observer [observer], date components
  /// ([ano], [mes], [dia]), and optional inventory type character [typeChar].
  ///
  /// The ID prefix is built as
  /// `[<local>-]<observer>-<year><month><day>-[<typeChar>]`.
  /// If no existing inventory matches the prefix, returns `1`.
  Future<int> getNextSequentialNumber(String? local, String observer, int ano, int mes, int dia, String? typeChar) async {
    final db = await _dbHelper.database;

    final prefix = "${local != null ? '$local-' : ''}$observer-$ano${mes.toString().padLeft(2, '0')}${dia.toString().padLeft(2, '0')}-${typeChar ?? ''}";

    final results = await db?.query(
      'inventories',
      where: 'id LIKE ?',
      whereArgs: ["$prefix%"],
      orderBy: 'id DESC',
      limit: 1,
    );

    if (results!.isNotEmpty) {
      final lastInventoryId = results.first['id'] as String;
      final sequentialNumberString = lastInventoryId.replaceFirst(prefix, '');
      final sequentialNumber = int.tryParse(sequentialNumberString) ?? 0;
      return sequentialNumber + 1;
    } else {
      return 1;
    }
  }

  /// Returns a sorted list of distinct locality names recorded across all
  /// inventories, excluding `null` values.
  ///
  /// Returns an empty list if the database is unavailable or an error occurs.
  Future<List<String>> getDistinctLocalities() async {
    try {
      final db = await _dbHelper.database;

      if (db == null) {
        throw Exception('Database is not available');
      }

      final List<Map<String, Object?>> results = await db.query(
        'inventories',
        distinct: true,
        columns: ['localityName'],
        where: 'localityName IS NOT NULL', // Ensure we only retrieve non-null locality names
      );

      final localities = results.map((row) => row['localityName'] as String).toList();
      localities.sort();
      
      debugPrint('[DAO] Distinct localities from inventories: $localities');
      return localities;
    } catch (e, s) {
      debugPrint('[DAO] !!! ERROR fetching inventories distinct localities: $e\n$s');
      return [];
    }
  }

  /// Returns a summary list of all [Inventory] records including aggregate
  /// species counts (`speciesCount`, `speciesWithinCount`,
  /// `speciesOutOfInventoryCount`), but without loading the full [Species],
  /// [Vegetation], or [Weather] sub-lists.
  Future<List<Inventory>> getInventoriesSummary() async {
    final db = await _dbHelper.database;
    try {
      // JOIN LEFT com COUNT de espécies para preencher especiesCount
      final List<Map<String, dynamic>> maps = await db?.rawQuery('''
        SELECT 
          i.*,
          COUNT(s.id) as speciesCount,
          COUNT(CASE WHEN s.isOutOfInventory = 0 THEN 1 END) as speciesWithinCount,
          COUNT(CASE WHEN s.isOutOfInventory = 1 THEN 1 END) as speciesOutOfInventoryCount
        FROM inventories i
        LEFT JOIN species s ON s.inventoryId = i.id
        GROUP BY i.id
      ''') ?? [];

      List<Inventory> inventories = maps.map((map) {
        final speciesCount = map['speciesCount'] as int? ?? 0;
        final speciesWithinCount = map['speciesWithinCount'] as int? ?? 0;
        final speciesOutOfInventoryCount =
            map['speciesOutOfInventoryCount'] as int? ?? 0;
        // Cria inventário sem especies/vegetação/clima
        return Inventory.fromMap(
          map,
          [],
          [],
          [],
          speciesCount: speciesCount,
          speciesWithinCount: speciesWithinCount,
          speciesOutOfInventoryCount: speciesOutOfInventoryCount,
        );
      }).toList();

      debugPrint('[DAO] Loaded inventories summary: ${inventories.length}');
      return inventories;
    } catch (e) {
      debugPrint('[DAO] !!! ERROR loading inventories summary: $e');
      return [];
    }
  }

  /// Returns the set of inventory IDs that contain at least one [Species]
  /// record whose name matches [speciesName].
  ///
  /// Uses a direct SQL query to avoid loading all data into memory.
  Future<Set<String>> getInventoryIdsBySpecies(String speciesName) async {
    final db = await _dbHelper.database;
    try {
      final List<Map<String, dynamic>> maps =
      await db?.query(
          'species',
          columns: ['inventoryId'],
          where: 'name = ?',
          whereArgs: [speciesName],
          distinct: true,
      ) ?? [];

      return maps
          .map((m) => m['inventoryId'] as String?)
          .whereType<String>()
          .toSet();
    } catch (e) {
      debugPrint('[DAO] !!! ERROR fetching inventory IDs by species: $e');
      return <String>{};
    }
  }

  /// Returns all [Inventory] records that contain at least one [Species] whose
  /// name matches [speciesName], each populated with its full [Species] list.
  Future<List<Inventory>> getInventoriesBySpecies(String speciesName) async {
    final db = await _dbHelper.database;
    try {
      // SQL query que busca direto: inventários que contêm a espécie
      final List<Map<String, dynamic>> maps = await db?.rawQuery('''
        SELECT DISTINCT i.* 
        FROM inventories i
        INNER JOIN species s ON s.inventoryId = i.id
        WHERE s.name = ?
      ''', [speciesName]) ?? [];

      List<Inventory> inventories = [];
      for (var map in maps) {
        // Para a lista de filtro, pode carregar só a espécie filtrada
        List<Species> filteredSpecies = await _speciesDao.getSpeciesByInventory(map['id'], false);
        inventories.add(Inventory.fromMap(map, filteredSpecies, [], []));
      }

      debugPrint('[DAO] Loaded ${inventories.length} inventories with species: $speciesName');
      return inventories;
    } catch (e) {
      debugPrint('[DAO] !!! ERROR loading inventories by species: $e');
      return [];
    }
  }

  /// Returns the total number of sampling hours across all finished inventories,
  /// calculated directly in SQL.
  Future<double> getTotalSamplingHours_SQL() async {
    final db = await _dbHelper.database;
    try {
      // Cálculo direto no DB, bem mais rápido
      final result = await db?.rawQuery('''
        SELECT 
          SUM((julianday(endTime) - julianday(startTime)) * 24) as totalHours
        FROM inventories
        WHERE isFinished = 1 AND endTime IS NOT NULL AND startTime IS NOT NULL
      ''');

      if (result != null && result.isNotEmpty) {
        final hours = result.first['totalHours'] as double? ?? 0.0;
        debugPrint('[DAO] Total sampling hours (SQL): $hours');
        return hours;
      }
      return 0.0;
    } catch (e) {
      debugPrint('[DAO] !!! ERROR calculating sampling hours: $e');
      return 0.0;
    }
  }

  /// Returns the total number of distinct sampling days across all finished
  /// inventories, calculated directly in SQL.
  Future<int> getTotalSamplingDays_SQL() async {
    final db = await _dbHelper.database;
    try {
      // Conta dias distintos quando houver inventários finalizados
      final result = await db?.rawQuery('''
        SELECT COUNT(DISTINCT date(startTime)) as totalDays
        FROM inventories
        WHERE isFinished = 1 AND startTime IS NOT NULL
      ''');

      if (result != null && result.isNotEmpty) {
        final days = result.first['totalDays'] as int? ?? 0;
        debugPrint('[DAO] Total sampling days (SQL): $days');
        return days;
      }
      return 0;
    } catch (e) {
      debugPrint('[DAO] !!! ERROR calculating sampling days: $e');
      return 0;
    }
  }

  /// Returns the average sampling duration in hours across all finished
  /// inventories, calculated directly in SQL.
  Future<double> getAverageSamplingHours_SQL() async {
    final db = await _dbHelper.database;
    try {
      final result = await db?.rawQuery('''
        SELECT 
          AVG((julianday(endTime) - julianday(startTime)) * 24) as avgHours
        FROM inventories
        WHERE isFinished = 1 AND endTime IS NOT NULL AND startTime IS NOT NULL
      ''');

      if (result != null && result.isNotEmpty) {
        final hours = result.first['avgHours'] as double? ?? 0.0;
        debugPrint('[DAO] Average sampling hours (SQL): $hours');
        return hours;
      }
      return 0.0;
    } catch (e) {
      debugPrint('[DAO] !!! ERROR calculating average sampling hours: $e');
      return 0.0;
    }
  }

  /// Returns a sorted list of distinct species names recorded across all
  /// inventories, suitable for use in filter dropdowns.
  Future<List<String>> getUniqueSpeciesNames() async {
    final db = await _dbHelper.database;
    try {
      final result = await db?.rawQuery('''
        SELECT DISTINCT s.name 
        FROM species s
        INNER JOIN inventories i ON s.inventoryId = i.id
        ORDER BY s.name ASC
      ''') ?? [];

      final speciesNames = result.map((r) => r['name'] as String).toList();
      debugPrint('[DAO] Found ${speciesNames.length} unique species');
      return speciesNames;
    } catch (e) {
      debugPrint('[DAO] !!! ERROR fetching unique species: $e');
      return [];
    }
  }
}
